### PR TITLE
Fix Hotwire posts in RSS feed

### PR DESCRIPTION
**Pull request by rhannequin**
## Context

[Hotwire newsletters](https://masilotti.com/hotwire) are not visible from the [RSS feed](https://masilotti.com/feed.xml).

## Issues

- Hotwire newsletter posts are missing the date in their file name
- They must be inside a `_posts` folder
- They must be in `hotwire` directory to be considered as a category and target as such in `hotwire.html`

## Solution

- ~Fixed 2022 dates to 2021~ Edit: Already fixed by author
- Added dates in Hotwire posts file names
- Moved posts from `_hotwire` to `hotwire/_posts`

### CODE REVIEW

**Comment by joemasilotti** [comment]
Thanks for the contribution! Especially those date fixes.

I didn't know that the feed was generated from `_posts`, TIL. The only problem with this approach is the home page now shows the newsletters as blog articles. Is there any way to get around that and have it look like it was before?

**Comment by rhannequin** [comment]
Hello, sorry for the late reply.

Indeed, Hotwire posts are now visible from the homepage, as it's retrieving the 5 latest posts:

```rb
{% for post in site.posts limit:5 %}
```

TBH I don't know how to find the best solution, as:
- Hotwire posts are currently absent from the RSS feed because they are not seen as posts but pages
- As long as they are seen as posts, they are included in `site.posts`

**Comment by joemasilotti** [comment]
Hmm. What if we include them as posts but ignore them on the homepage? I think they have a special front matter key or attribute we could switch on.

**Comment by rhannequin** [comment]
I thought it f that, but I thought you wouldn't be inclined to have something like "every post but this kind of posts" on the homepage as it doesn't look like the best thing if your blow grows with multiple new categories.

**Comment by joemasilotti** [comment]
I think that for now that is preferred. The exclusion is only because the Hotwire stuff is technically a newsletter, not a specific type of post.

**Comment by rhannequin** [comment]
@joemasilotti Here is another proposal, which works as you want to.
This is not the best code I have ever seen, especially with the counter thing, but it is the only way I found to ensure `hotwire` posts were not displayed on the homepage, and only 5 "not hotwire" posts were displayed.
What do you think?

**Comment by joemasilotti** [comment]
Would something like this work?

```
{% assign posts = site.posts | where: "layout", "post" %}
{% for post in posts limit:5 %}
```

**Comment by rhannequin** [comment]
Unfortunately I did not find how to use `where` to query for posts which category does not contain "hotwire".
I tried the following:
`{% assign posts = site.posts | where: "item", "item.categories not contain 'hotwire'" %}`
But it is ignored

**Comment by joemasilotti** [comment]
I don't think it's possible. That's why I'm filtering by layout of "post" instead in the snippet.

**Comment by rhannequin** [comment]
I have no idea how `where: "layout", "post"` works but indeed, it works.
Well, for a first PR here, it was quite laborious :facepalm:

**Comment by joemasilotti** [comment]
I _think_ it's matching the `layout` key in the front matter of each post. And since the Hotwire newsletters use the `hotwire` layout they are excluded.

Regardless, thanks so much for the PR! this was sneakily tricky. 😆

**Pull request merged**
